name: Docker Build Test_KCC

on:
  push:
    branches: [ main,KCH_ci_test ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Source Code Checkout
      uses: actions/checkout@v2
      
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: chaeheekang
        password: ${{ secrets.KCH_SECRET_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/chaeheekang/chuucarbot:0.1
