name: Docker Build Test_KCC

on:
  push:
    branches: [ main,KCH_ci_test ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Source Code Checkout
      uses: actions/checkout@master
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: chaeheekang
        password: ${{ secrets.KCH_SECRET_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/chaeheekang/chuucarbot:0.1
